//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DataDictionary", typeof(DataDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutButton {
            get {
                return ResourceManager.GetString("AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string AccessButton {
            get {
                return ResourceManager.GetString("AccessButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Users Form.
        /// </summary>
        public static string AccessForm {
            get {
                return ResourceManager.GetString("AccessForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Request.
        /// </summary>
        public static string AddToRequestButton {
            get {
                return ResourceManager.GetString("AddToRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Shoping.
        /// </summary>
        public static string AddToShopingButton {
            get {
                return ResourceManager.GetString("AddToShopingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string BackupButton {
            get {
                return ResourceManager.GetString("BackupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Form.
        /// </summary>
        public static string BackupForm {
            get {
                return ResourceManager.GetString("BackupForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string CountLabel {
            get {
                return ResourceManager.GetString("CountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string CountriesButton {
            get {
                return ResourceManager.GetString("CountriesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CustomerCode {
            get {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string CustomerFirstName {
            get {
                return ResourceManager.GetString("CustomerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Form.
        /// </summary>
        public static string CustomerForm {
            get {
                return ResourceManager.GetString("CustomerForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string CustomerLabel {
            get {
                return ResourceManager.GetString("CustomerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string CustomerLastName {
            get {
                return ResourceManager.GetString("CustomerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string CustomersButton {
            get {
                return ResourceManager.GetString("CustomersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers Form.
        /// </summary>
        public static string CustomersForm {
            get {
                return ResourceManager.GetString("CustomersForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        public static string CustomerTel {
            get {
                return ResourceManager.GetString("CustomerTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string EnterButton {
            get {
                return ResourceManager.GetString("EnterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitButton {
            get {
                return ResourceManager.GetString("ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factors.
        /// </summary>
        public static string FactorInMainFormButton {
            get {
                return ResourceManager.GetString("FactorInMainFormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Transfer Register.
        /// </summary>
        public static string InventoryTransferButton {
            get {
                return ResourceManager.GetString("InventoryTransferButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers.
        /// </summary>
        public static string InventoryTransferInMainFormButton {
            get {
                return ResourceManager.GetString("InventoryTransferInMainFormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Register.
        /// </summary>
        public static string InvoiceButton {
            get {
                return ResourceManager.GetString("InvoiceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice New.
        /// </summary>
        public static string InvoiceNewButton {
            get {
                return ResourceManager.GetString("InvoiceNewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فارسی.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginForm {
            get {
                return ResourceManager.GetString("LoginForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter/Exit.
        /// </summary>
        public static string LoginsHistorButton {
            get {
                return ResourceManager.GetString("LoginsHistorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maesure Units.
        /// </summary>
        public static string MaesureUnitsButton {
            get {
                return ResourceManager.GetString("MaesureUnitsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory System.
        /// </summary>
        public static string MainForm {
            get {
                return ResourceManager.GetString("MainForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MenuButton {
            get {
                return ResourceManager.GetString("MenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string MessagesButton {
            get {
                return ResourceManager.GetString("MessagesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string MessagesInMainFormButton {
            get {
                return ResourceManager.GetString("MessagesInMainFormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string NumberLabel {
            get {
                return ResourceManager.GetString("NumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordButton {
            get {
                return ResourceManager.GetString("PasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Setting Form.
        /// </summary>
        public static string PasswordForm {
            get {
                return ResourceManager.GetString("PasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Managment.
        /// </summary>
        public static string PriceManagmentToolStripMenuItem {
            get {
                return ResourceManager.GetString("PriceManagmentToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Inventory Receipt.
        /// </summary>
        public static string PrintInventoryReceiptButton {
            get {
                return ResourceManager.GetString("PrintInventoryReceiptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Inventory Transfer.
        /// </summary>
        public static string PrintInventoryTransferButton {
            get {
                return ResourceManager.GetString("PrintInventoryTransferButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Invoice.
        /// </summary>
        public static string PrintInvoiceButton {
            get {
                return ResourceManager.GetString("PrintInvoiceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Date.
        /// </summary>
        public static string ProductBuyDate {
            get {
                return ResourceManager.GetString("ProductBuyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string ProductCount {
            get {
                return ResourceManager.GetString("ProductCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string ProductCountry {
            get {
                return ResourceManager.GetString("ProductCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Edit.
        /// </summary>
        public static string ProductEditButton {
            get {
                return ResourceManager.GetString("ProductEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ProductImage {
            get {
                return ResourceManager.GetString("ProductImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        public static string ProductInvoiceNo {
            get {
                return ResourceManager.GetString("ProductInvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Price.
        /// </summary>
        public static string ProductLastPrice {
            get {
                return ResourceManager.GetString("ProductLastPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Stock.
        /// </summary>
        public static string ProductLastStock {
            get {
                return ResourceManager.GetString("ProductLastStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product New.
        /// </summary>
        public static string ProductNewButton {
            get {
                return ResourceManager.GetString("ProductNewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductPrice Form.
        /// </summary>
        public static string ProductPriceForm {
            get {
                return ResourceManager.GetString("ProductPriceForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Date.
        /// </summary>
        public static string ProductRegisterDate {
            get {
                return ResourceManager.GetString("ProductRegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar.
        /// </summary>
        public static string ProductRegistrar {
            get {
                return ResourceManager.GetString("ProductRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string ProductsButton {
            get {
                return ResourceManager.GetString("ProductsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Form.
        /// </summary>
        public static string ProductsForm {
            get {
                return ResourceManager.GetString("ProductsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active/DeActive.
        /// </summary>
        public static string ProductStatusButton {
            get {
                return ResourceManager.GetString("ProductStatusButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string ProductStock {
            get {
                return ResourceManager.GetString("ProductStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductStock Form.
        /// </summary>
        public static string ProductStockForm {
            get {
                return ResourceManager.GetString("ProductStockForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Kepper.
        /// </summary>
        public static string ProductStoreKepper {
            get {
                return ResourceManager.GetString("ProductStoreKepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storeroom.
        /// </summary>
        public static string ProductStoreroom {
            get {
                return ResourceManager.GetString("ProductStoreroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppler.
        /// </summary>
        public static string ProductSuppler {
            get {
                return ResourceManager.GetString("ProductSuppler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string ProductUnit {
            get {
                return ResourceManager.GetString("ProductUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Sales.
        /// </summary>
        public static string ProductUnitSales {
            get {
                return ResourceManager.GetString("ProductUnitSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar.
        /// </summary>
        public static string RegistrarLabel {
            get {
                return ResourceManager.GetString("RegistrarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportsButton {
            get {
                return ResourceManager.GetString("ReportsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportsInMainFormButton {
            get {
                return ResourceManager.GetString("ReportsInMainFormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Form.
        /// </summary>
        public static string RequestForm {
            get {
                return ResourceManager.GetString("RequestForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string RequestInMainFormButton {
            get {
                return ResourceManager.GetString("RequestInMainFormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string RequestProductCount {
            get {
                return ResourceManager.GetString("RequestProductCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string RequestProductName {
            get {
                return ResourceManager.GetString("RequestProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Price.
        /// </summary>
        public static string RequestProductPrice {
            get {
                return ResourceManager.GetString("RequestProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string RequestProductUnit {
            get {
                return ResourceManager.GetString("RequestProductUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string RequestRow {
            get {
                return ResourceManager.GetString("RequestRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string RequestsButton {
            get {
                return ResourceManager.GetString("RequestsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rials.
        /// </summary>
        public static string RialsLabel {
            get {
                return ResourceManager.GetString("RialsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchCustomerLabel {
            get {
                return ResourceManager.GetString("SearchCustomerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchProductLabel {
            get {
                return ResourceManager.GetString("SearchProductLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopings.
        /// </summary>
        public static string ShopingInMainFormButton {
            get {
                return ResourceManager.GetString("ShopingInMainFormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockManagment.
        /// </summary>
        public static string StockManagmentToolStripMenuItem {
            get {
                return ResourceManager.GetString("StockManagmentToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storekeepers.
        /// </summary>
        public static string StorekeepersButton {
            get {
                return ResourceManager.GetString("StorekeepersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storerooms .
        /// </summary>
        public static string StoreroomsButton {
            get {
                return ResourceManager.GetString("StoreroomsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplers.
        /// </summary>
        public static string SupplersButton {
            get {
                return ResourceManager.GetString("SupplersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplers Form.
        /// </summary>
        public static string SupplersForm {
            get {
                return ResourceManager.GetString("SupplersForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory System.
        /// </summary>
        public static string SystemNameLabel {
            get {
                return ResourceManager.GetString("SystemNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string TotalAmountLabel {
            get {
                return ResourceManager.GetString("TotalAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string UserActive {
            get {
                return ResourceManager.GetString("UserActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string UserAge {
            get {
                return ResourceManager.GetString("UserAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string UserBirthdate {
            get {
                return ResourceManager.GetString("UserBirthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string UserDescription {
            get {
                return ResourceManager.GetString("UserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Edit.
        /// </summary>
        public static string UserEditButton {
            get {
                return ResourceManager.GetString("UserEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate.
        /// </summary>
        public static string UserEndDate {
            get {
                return ResourceManager.GetString("UserEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string UserFirstName {
            get {
                return ResourceManager.GetString("UserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string UserGender {
            get {
                return ResourceManager.GetString("UserGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string UserLastName {
            get {
                return ResourceManager.GetString("UserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User New.
        /// </summary>
        public static string UserNewButton {
            get {
                return ResourceManager.GetString("UserNewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersButton {
            get {
                return ResourceManager.GetString("UsersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Users Form.
        /// </summary>
        public static string UsersForm {
            get {
                return ResourceManager.GetString("UsersForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string UserStartDate {
            get {
                return ResourceManager.GetString("UserStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active/DeActive.
        /// </summary>
        public static string UserStatusButton {
            get {
                return ResourceManager.GetString("UserStatusButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        public static string UserTel {
            get {
                return ResourceManager.GetString("UserTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserUsername {
            get {
                return ResourceManager.GetString("UserUsername", resourceCulture);
            }
        }
    }
}
