using System.Resources;
using Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace MyApplication
{
    public partial class MadeinCountriesForm : Usf.WinForms.Forms.Form
    {
        Persistence.DatabaseContext dbContext = new Persistence.DatabaseContext();

        public MadeinCountriesForm()
        {
            InitializeComponent();

            #region Language

            ResourceManager resource = new ResourceManager
               ("Resources.DataDictionary", typeof(Resources.DataDictionary).Assembly);

            this.Text =
                resource.GetString(name: nameof(MadeinCountriesForm));

            #endregion / Language
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.MadeInCountries.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.MadeInCountries.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        // Loaded
        private void CustomerForm_Load(object sender, EventArgs e)
        {
            if (ApplicationSettings.CurrentCulture == ApplicationSettings.Languages.Farsi)
            {
                this.RightToLeft = RightToLeft.Yes;
                this.RightToLeftLayout = true;
            }
        }

        private void buttonSimlpe1_Click(object sender, EventArgs e)
        {
            var country = new MadeInCountry
            {
                Id = Guid.NewGuid(),
                Name = textEdit1.Text,
                InsertDateTime = DateTime.Now,
                IsActive = true,
                IsDeleted = false,
                UsernameId = Program.usernameid,
            };
            dbContext.MadeInCountries.AddAsync(country);
            dbContext.SaveChangesAsync();
            gridControl1.RefreshDataSource();
        }
    }
}